/**
 * Named theme registry for the omp GUI.
 *
 * Every theme defines the exact same set of `--omp-*` design tokens (see
 * THEME_TOKEN_KEYS — the canonical 119 keys shared with theme-dark.css and
 * theme-light.css). `dark` and `light` are ports of those stylesheets; the
 * remaining themes are original palettes. applyThemeByName() writes the full
 * token map as inline custom properties on <html> (beating the `:root`
 * stylesheet rules), keeps `data-theme` / the color-scheme meta in sync via
 * lib/theme's applyTheme(), and persists the selection under the
 * `themeName` pref (plus the legacy `theme` pref for backwards compat).
 * "system" is a special selection that resolves to dark or light via the OS
 * media query and stays stylesheet-driven.
 *
 * On top of the named themes sits the agent theme overlay (bottom of this
 * file): the coding-agent's `theme.dark` / `theme.light` settings name TUI
 * themes whose resolved colors are translated onto a subset of the same
 * tokens (see TRANSCRIPT_OVERLAY_VARS) and layered inline over the active GUI
 * theme, re-synced on config_update frames and data-theme flips.
 */

import type { RpcThemeColorsResult } from "../../shared/rpc-types";
import { acceptsActiveTabEvents, onActiveTabRouteSettled } from "./tab-routing";
import { applyTheme, markCustomThemeTokens, resolveTheme } from "./theme";

/** Canonical token keys, in stylesheet order. Every theme defines all of them. */
export const THEME_TOKEN_KEYS = [
	"--omp-accent",
	"--omp-accent-bright",
	"--omp-accent-dim",
	"--omp-accent-glow",
	"--omp-border",
	"--omp-border-accent",
	"--omp-border-muted",
	"--omp-border-strong",
	"--omp-success",
	"--omp-success-dim",
	"--omp-error",
	"--omp-error-dim",
	"--omp-warning",
	"--omp-warning-dim",
	"--omp-info",
	"--omp-info-dim",
	"--omp-text",
	"--omp-text-secondary",
	"--omp-bg-primary",
	"--omp-bg-secondary",
	"--omp-bg-tertiary",
	"--omp-bg-elevated",
	"--omp-selected-bg",
	"--omp-user-msg-bg",
	"--omp-user-msg-border",
	"--omp-custom-msg-bg",
	"--omp-code-bg",
	"--omp-tool-pending-bg",
	"--omp-tool-success-bg",
	"--omp-tool-error-bg",
	"--omp-tool-output",
	"--omp-tool-rail-running",
	"--omp-tool-rail-done",
	"--omp-tool-rail-error",
	"--omp-md-heading",
	"--omp-md-link",
	"--omp-md-link-url",
	"--omp-md-code",
	"--omp-md-code-block",
	"--omp-md-code-block-border",
	"--omp-md-quote",
	"--omp-md-quote-border",
	"--omp-md-hr",
	"--omp-md-list-bullet",
	"--omp-diff-added",
	"--omp-diff-added-bg",
	"--omp-diff-removed",
	"--omp-diff-removed-bg",
	"--omp-diff-context",
	"--omp-syntax-comment",
	"--omp-syntax-keyword",
	"--omp-syntax-function",
	"--omp-syntax-variable",
	"--omp-syntax-string",
	"--omp-syntax-number",
	"--omp-syntax-type",
	"--omp-syntax-operator",
	"--omp-syntax-punctuation",
	"--omp-thinking-off",
	"--omp-thinking-minimal",
	"--omp-thinking-low",
	"--omp-thinking-medium",
	"--omp-thinking-high",
	"--omp-thinking-xhigh",
	"--omp-status-bg",
	"--omp-status-model",
	"--omp-status-path",
	"--omp-status-git-clean",
	"--omp-status-git-dirty",
	"--omp-status-context",
	"--omp-status-spend",
	"--omp-status-subagents",
	"--omp-status-muted",
	"--omp-status-dim",
	"--omp-status-text",
	"--omp-status-sep",
	"--omp-muted",
	"--omp-dim",
	"--omp-link",
	"--omp-custom-msg-label",
	"--omp-input-bg",
	"--omp-input-border",
	"--omp-input-focus-border",
	"--omp-input-glow",
	"--omp-btn-primary-bg",
	"--omp-btn-primary-text",
	"--omp-btn-secondary-bg",
	"--omp-btn-secondary-text",
	"--omp-btn-danger-bg",
	"--omp-btn-danger-text",
	"--omp-badge-bg",
	"--omp-badge-text",
	"--omp-badge-accent",
	"--omp-overlay-bg",
	"--omp-modal-bg",
	"--omp-modal-border",
	"--omp-toast-bg",
	"--omp-toast-text",
	"--omp-toast-border",
	"--omp-progress-bg",
	"--omp-progress-fill",
	"--omp-sidebar-bg",
	"--omp-sidebar-item-hover",
	"--omp-sidebar-item-active",
	"--omp-selection-bg",
	"--omp-selection-text",
	"--omp-scrollbar-thumb",
	"--omp-scrollbar-track",
	"--omp-streaming-cursor",
	"--omp-streaming-highlight",
	"--omp-panel-bg",
	"--omp-panel-border",
	"--omp-panel-header",
	"--omp-titlebar-bg",
	"--omp-titlebar-text",
	"--omp-shadow-sm",
	"--omp-shadow-md",
	"--omp-shadow-lg",
	"--omp-shadow-glow",
] as const;

export type ThemeTokenKey = (typeof THEME_TOKEN_KEYS)[number];
export type ThemeTokens = Record<ThemeTokenKey, string>;

export interface ThemeDefinition {
	/** Human-readable name shown in the picker. */
	label: string;
	/** One-line picker blurb. */
	description: string;
	/** Base color scheme — drives data-theme, the color-scheme meta, and native controls. */
	scheme: "dark" | "light";
	tokens: ThemeTokens;
}

const dark: ThemeDefinition = {
	label: "Dark",
	description: "Cool graphite surfaces with a periwinkle accent.",
	scheme: "dark",
	tokens: {
		"--omp-accent": "#8f9bff",
		"--omp-accent-bright": "#b1baff",
		"--omp-accent-dim": "rgba(143, 155, 251, 0.16)",
		"--omp-accent-glow": "rgba(143, 155, 251, 0.28)",
		"--omp-border": "#2e3550",
		"--omp-border-accent": "rgba(143, 155, 251, 0.5)",
		"--omp-border-muted": "#242a42",
		"--omp-border-strong": "#454e6e",
		"--omp-success": "#4ade80",
		"--omp-success-dim": "rgba(74, 222, 128, 0.12)",
		"--omp-error": "#f87171",
		"--omp-error-dim": "rgba(248, 113, 113, 0.12)",
		"--omp-warning": "#fbbf24",
		"--omp-warning-dim": "rgba(251, 191, 36, 0.12)",
		"--omp-info": "#8f9bff",
		"--omp-info-dim": "rgba(143, 155, 251, 0.12)",
		"--omp-text": "#eef0fa",
		"--omp-text-secondary": "#c0c8de",
		"--omp-bg-primary": "#101219",
		"--omp-bg-secondary": "#151927",
		"--omp-bg-tertiary": "#1c2133",
		"--omp-bg-elevated": "#262c45",
		"--omp-selected-bg": "rgba(143, 155, 251, 0.13)",
		"--omp-user-msg-bg": "rgba(143, 155, 251, 0.09)",
		"--omp-user-msg-border": "rgba(143, 155, 251, 0.22)",
		"--omp-custom-msg-bg": "#1c2135",
		"--omp-code-bg": "#0c0f18",
		"--omp-tool-pending-bg": "#171d31",
		"--omp-tool-success-bg": "#14271c",
		"--omp-tool-error-bg": "#2b1a22",
		"--omp-tool-output": "#c7d0dd",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#427253",
		"--omp-tool-rail-error": "#8a4a52",
		"--omp-md-heading": "#ffffff",
		"--omp-md-link": "#b1baff",
		"--omp-md-link-url": "#95a1b5",
		"--omp-md-code": "#f0a3b8",
		"--omp-md-code-block": "#dce5f4",
		"--omp-md-code-block-border": "#2e3550",
		"--omp-md-quote": "#bdc7d5",
		"--omp-md-quote-border": "#4d5878",
		"--omp-md-hr": "#2e3550",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#4ade80",
		"--omp-diff-added-bg": "rgba(74, 222, 128, 0.09)",
		"--omp-diff-removed": "#f87171",
		"--omp-diff-removed-bg": "rgba(248, 113, 113, 0.09)",
		"--omp-diff-context": "#9aa5bc",
		"--omp-syntax-comment": "#7f8aa3",
		"--omp-syntax-keyword": "#93a4ff",
		"--omp-syntax-function": "#7dd3fc",
		"--omp-syntax-variable": "#e6eafb",
		"--omp-syntax-string": "#f0b075",
		"--omp-syntax-number": "#5eead4",
		"--omp-syntax-type": "#aab4ff",
		"--omp-syntax-operator": "#d7dbea",
		"--omp-syntax-punctuation": "#8b95b5",
		"--omp-thinking-off": "#5d6880",
		"--omp-thinking-minimal": "#748199",
		"--omp-thinking-low": "#6b79b8",
		"--omp-thinking-medium": "#8f9bff",
		"--omp-thinking-high": "#aab4ff",
		"--omp-thinking-xhigh": "#cdd3ff",
		"--omp-status-bg": "#0c0f17",
		"--omp-status-model": "#c0c8de",
		"--omp-status-path": "#93a4ff",
		"--omp-status-git-clean": "#4ade80",
		"--omp-status-git-dirty": "#fbbf24",
		"--omp-status-context": "#8f9bff",
		"--omp-status-spend": "#93a4ff",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#8a94b0",
		"--omp-status-dim": "#5d6880",
		"--omp-status-text": "#eef0fa",
		"--omp-status-sep": "#2e3550",
		"--omp-muted": "#a9b4c9",
		"--omp-dim": "#7d87a3",
		"--omp-link": "#b1baff",
		"--omp-custom-msg-label": "#b1baff",
		"--omp-input-bg": "#161b2b",
		"--omp-input-border": "#333b5a",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(143, 155, 251, 0.18)",
		"--omp-btn-primary-bg": "#eef0fa",
		"--omp-btn-primary-text": "#14161f",
		"--omp-btn-secondary-bg": "#242a42",
		"--omp-btn-secondary-text": "#eef0fa",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#08152f",
		"--omp-badge-bg": "#252c46",
		"--omp-badge-text": "#c4cbe0",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(5, 7, 12, 0.72)",
		"--omp-modal-bg": "#1a1f31",
		"--omp-modal-border": "#333b58",
		"--omp-toast-bg": "#1a1f31",
		"--omp-toast-text": "#eef0fa",
		"--omp-toast-border": "#333b58",
		"--omp-progress-bg": "#252c46",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#121624",
		"--omp-sidebar-item-hover": "#1c2234",
		"--omp-sidebar-item-active": "#262e4c",
		"--omp-selection-bg": "rgba(143, 155, 251, 0.26)",
		"--omp-selection-text": "#eef0fa",
		"--omp-scrollbar-thumb": "#454e6e",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(143, 155, 251, 0.07)",
		"--omp-panel-bg": "#161b2b",
		"--omp-panel-border": "#242a42",
		"--omp-panel-header": "#a9b4c9",
		"--omp-titlebar-bg": "#141828",
		"--omp-titlebar-text": "#eef0fa",
		"--omp-shadow-sm": "0 1px 2px rgba(0, 0, 0, 0.42)",
		"--omp-shadow-md": "0 6px 20px rgba(0, 0, 0, 0.5)",
		"--omp-shadow-lg": "0 18px 48px rgba(0, 0, 0, 0.6)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 22px var(--omp-input-glow)",
	},
};

const light: ThemeDefinition = {
	label: "Light",
	description: "Airy cool-white neutrals with a vivid indigo accent.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#4c5ef2",
		"--omp-accent-bright": "#6b7bff",
		"--omp-accent-dim": "rgba(76, 94, 242, 0.08)",
		"--omp-accent-glow": "rgba(76, 94, 242, 0.16)",
		"--omp-border": "#dcdfe8",
		"--omp-border-accent": "rgba(76, 94, 242, 0.4)",
		"--omp-border-muted": "#e8eaf1",
		"--omp-border-strong": "#c2c7d6",
		"--omp-success": "#16a34a",
		"--omp-success-dim": "rgba(22, 163, 74, 0.09)",
		"--omp-error": "#e5484d",
		"--omp-error-dim": "rgba(229, 72, 77, 0.08)",
		"--omp-warning": "#d97706",
		"--omp-warning-dim": "rgba(217, 119, 6, 0.09)",
		"--omp-info": "#4c5ef2",
		"--omp-info-dim": "rgba(76, 94, 242, 0.08)",
		"--omp-text": "#17191f",
		"--omp-text-secondary": "#4f5562",
		"--omp-bg-primary": "#f8f9fb",
		"--omp-bg-secondary": "#f1f3f7",
		"--omp-bg-tertiary": "#e9ebf2",
		"--omp-bg-elevated": "#ffffff",
		"--omp-selected-bg": "#e9ecfd",
		"--omp-user-msg-bg": "rgba(76, 94, 242, 0.055)",
		"--omp-user-msg-border": "rgba(76, 94, 242, 0.16)",
		"--omp-custom-msg-bg": "#eef0f8",
		"--omp-code-bg": "#eff1f6",
		"--omp-tool-pending-bg": "#f4f5f9",
		"--omp-tool-success-bg": "#ebf7f0",
		"--omp-tool-error-bg": "#fbeff0",
		"--omp-tool-output": "#55606b",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#4daa75",
		"--omp-tool-rail-error": "#d0707a",
		"--omp-md-heading": "#14161b",
		"--omp-md-link": "#4c5ef2",
		"--omp-md-link-url": "#7d8590",
		"--omp-md-code": "#b03a5b",
		"--omp-md-code-block": "#343a46",
		"--omp-md-code-block-border": "#dcdfe8",
		"--omp-md-quote": "#5b6472",
		"--omp-md-quote-border": "#c9cedd",
		"--omp-md-hr": "#dcdfe8",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#16a34a",
		"--omp-diff-added-bg": "rgba(22, 163, 74, 0.08)",
		"--omp-diff-removed": "#e5484d",
		"--omp-diff-removed-bg": "rgba(229, 72, 77, 0.08)",
		"--omp-diff-context": "#6d7681",
		"--omp-syntax-comment": "#8a9199",
		"--omp-syntax-keyword": "#2563eb",
		"--omp-syntax-function": "#0891b2",
		"--omp-syntax-variable": "#1f2328",
		"--omp-syntax-string": "#b45309",
		"--omp-syntax-number": "#0d9488",
		"--omp-syntax-type": "#4c5ef2",
		"--omp-syntax-operator": "#4b5057",
		"--omp-syntax-punctuation": "#6d7681",
		"--omp-thinking-off": "#a4aab6",
		"--omp-thinking-minimal": "#8b93c8",
		"--omp-thinking-low": "#6d79d8",
		"--omp-thinking-medium": "#4c5ef2",
		"--omp-thinking-high": "#3d4bd6",
		"--omp-thinking-xhigh": "#2f3ab0",
		"--omp-status-bg": "#eff1f6",
		"--omp-status-model": "#4f5562",
		"--omp-status-path": "#4c5ef2",
		"--omp-status-git-clean": "#16a34a",
		"--omp-status-git-dirty": "#d97706",
		"--omp-status-context": "#4c5ef2",
		"--omp-status-spend": "#4c5ef2",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#7d8492",
		"--omp-status-dim": "#a4aab6",
		"--omp-status-text": "#17191f",
		"--omp-status-sep": "#dfe2ec",
		"--omp-muted": "#5d6470",
		"--omp-dim": "#6d7580",
		"--omp-link": "#4c5ef2",
		"--omp-custom-msg-label": "#4c5ef2",
		"--omp-input-bg": "#ffffff",
		"--omp-input-border": "#dcdfe8",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(76, 94, 242, 0.12)",
		"--omp-btn-primary-bg": "#1d2027",
		"--omp-btn-primary-text": "#ffffff",
		"--omp-btn-secondary-bg": "#eff1f6",
		"--omp-btn-secondary-text": "#17191f",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#eff1f6",
		"--omp-badge-text": "#525a68",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(23, 25, 38, 0.32)",
		"--omp-modal-bg": "#ffffff",
		"--omp-modal-border": "#e2e5ee",
		"--omp-toast-bg": "#ffffff",
		"--omp-toast-text": "#17191f",
		"--omp-toast-border": "#e2e5ee",
		"--omp-progress-bg": "#e6e8f0",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#f2f3f7",
		"--omp-sidebar-item-hover": "#ecedf3",
		"--omp-sidebar-item-active": "#e5e8f5",
		"--omp-selection-bg": "rgba(76, 94, 242, 0.14)",
		"--omp-selection-text": "#14161b",
		"--omp-scrollbar-thumb": "#c6c9d6",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(76, 94, 242, 0.05)",
		"--omp-panel-bg": "#f2f3f7",
		"--omp-panel-border": "#dcdfe8",
		"--omp-panel-header": "#5d6470",
		"--omp-titlebar-bg": "#f8f9fb",
		"--omp-titlebar-text": "#17191f",
		"--omp-shadow-sm": "0 1px 2px rgba(28, 30, 55, 0.05)",
		"--omp-shadow-md": "0 6px 20px rgba(28, 30, 55, 0.09)",
		"--omp-shadow-lg": "0 18px 48px rgba(28, 30, 55, 0.14)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 16px var(--omp-input-glow)",
	},
};

const titanium: ThemeDefinition = {
	label: "Titanium",
	description: "Mid-dark graphite with a steel-blue accent.",
	scheme: "dark",
	tokens: {
		"--omp-accent": "#86a8f0",
		"--omp-accent-bright": "#a3bdf5",
		"--omp-accent-dim": "rgba(134, 168, 240, 0.15)",
		"--omp-accent-glow": "rgba(134, 168, 240, 0.26)",
		"--omp-border": "#454c58",
		"--omp-border-accent": "rgba(134, 168, 240, 0.6)",
		"--omp-border-muted": "#383e48",
		"--omp-border-strong": "#596273",
		"--omp-success": "#5fd08a",
		"--omp-success-dim": "rgba(95, 208, 138, 0.12)",
		"--omp-error": "#ee7d7d",
		"--omp-error-dim": "rgba(238, 125, 125, 0.12)",
		"--omp-warning": "#f0c060",
		"--omp-warning-dim": "rgba(240, 192, 96, 0.12)",
		"--omp-info": "#7ab5f5",
		"--omp-info-dim": "rgba(122, 181, 245, 0.12)",
		"--omp-text": "#eef1f6",
		"--omp-text-secondary": "#bcc3cf",
		"--omp-bg-primary": "#22262c",
		"--omp-bg-secondary": "#282c33",
		"--omp-bg-tertiary": "#30353d",
		"--omp-bg-elevated": "#3a404a",
		"--omp-selected-bg": "#33425e",
		"--omp-user-msg-bg": "#2a3852",
		"--omp-user-msg-border": "#46618c",
		"--omp-custom-msg-bg": "#32304a",
		"--omp-code-bg": "#1e2228",
		"--omp-tool-pending-bg": "#27334a",
		"--omp-tool-success-bg": "#223a2c",
		"--omp-tool-error-bg": "#402831",
		"--omp-tool-output": "#c2cad6",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#50805f",
		"--omp-tool-rail-error": "#96555e",
		"--omp-md-heading": "#ffffff",
		"--omp-md-link": "#a5c2ff",
		"--omp-md-link-url": "#98a2b3",
		"--omp-md-code": "#d4aeff",
		"--omp-md-code-block": "#dde4f0",
		"--omp-md-code-block-border": "#454c58",
		"--omp-md-quote": "#bfc8d4",
		"--omp-md-quote-border": "#626e82",
		"--omp-md-hr": "#454c58",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#5fd08a",
		"--omp-diff-added-bg": "rgba(95, 208, 138, 0.09)",
		"--omp-diff-removed": "#ee7d7d",
		"--omp-diff-removed-bg": "rgba(238, 125, 125, 0.09)",
		"--omp-diff-context": "#9da7ba",
		"--omp-syntax-comment": "#8a9484",
		"--omp-syntax-keyword": "#86a8f0",
		"--omp-syntax-function": "#d4aeff",
		"--omp-syntax-variable": "#d8e0f5",
		"--omp-syntax-string": "#7fd8c8",
		"--omp-syntax-number": "#ecc280",
		"--omp-syntax-type": "#84cdf2",
		"--omp-syntax-operator": "#d8dce6",
		"--omp-syntax-punctuation": "#9da7ba",
		"--omp-thinking-off": "#707a8c",
		"--omp-thinking-minimal": "#8b95a8",
		"--omp-thinking-low": "#6fb0e0",
		"--omp-thinking-medium": "#a5c2ff",
		"--omp-thinking-high": "#c794e6",
		"--omp-thinking-xhigh": "#ecc9ff",
		"--omp-status-bg": "#1c2026",
		"--omp-status-model": "#bcc3cf",
		"--omp-status-path": "#7fd8c8",
		"--omp-status-git-clean": "#5fd08a",
		"--omp-status-git-dirty": "#f0c060",
		"--omp-status-context": "#a0abff",
		"--omp-status-spend": "#7fd8c8",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#8b95a8",
		"--omp-status-dim": "#707a8c",
		"--omp-status-text": "#eef1f6",
		"--omp-status-sep": "#3c4452",
		"--omp-muted": "#aab3c0",
		"--omp-dim": "#8b94a3",
		"--omp-link": "#a5c2ff",
		"--omp-custom-msg-label": "#86a8f0",
		"--omp-input-bg": "#282e37",
		"--omp-input-border": "#48505e",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(134, 168, 240, 0.17)",
		"--omp-btn-primary-bg": "var(--omp-accent)",
		"--omp-btn-primary-text": "#101c38",
		"--omp-btn-secondary-bg": "#383e48",
		"--omp-btn-secondary-text": "#eef1f6",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#101c38",
		"--omp-badge-bg": "#343c4c",
		"--omp-badge-text": "#c0c7d4",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(10, 13, 18, 0.72)",
		"--omp-modal-bg": "#2b3038",
		"--omp-modal-border": "#454e5c",
		"--omp-toast-bg": "#2b3038",
		"--omp-toast-text": "#eef1f6",
		"--omp-toast-border": "#454e5c",
		"--omp-progress-bg": "#343c4c",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#242932",
		"--omp-sidebar-item-hover": "#2d333d",
		"--omp-sidebar-item-active": "#333d52",
		"--omp-selection-bg": "rgba(134, 168, 240, 0.25)",
		"--omp-selection-text": "#eef1f6",
		"--omp-scrollbar-thumb": "#4d5666",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(134, 168, 240, 0.07)",
		"--omp-panel-bg": "#282d36",
		"--omp-panel-border": "#383e48",
		"--omp-panel-header": "#aab3c0",
		"--omp-titlebar-bg": "#252a32",
		"--omp-titlebar-text": "#eef1f6",
		"--omp-shadow-sm": "0 1px 2px rgba(0, 0, 0, 0.4)",
		"--omp-shadow-md": "0 5px 16px rgba(0, 0, 0, 0.45)",
		"--omp-shadow-lg": "0 16px 40px rgba(0, 0, 0, 0.55)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 20px var(--omp-input-glow)",
	},
};

const nord: ThemeDefinition = {
	label: "Nord",
	description: "Cool polar-night blues with a frost accent.",
	scheme: "dark",
	tokens: {
		"--omp-accent": "#88c0d0",
		"--omp-accent-bright": "#8fbcbb",
		"--omp-accent-dim": "rgba(136, 192, 208, 0.16)",
		"--omp-accent-glow": "rgba(136, 192, 208, 0.28)",
		"--omp-border": "#434c5e",
		"--omp-border-accent": "rgba(136, 192, 208, 0.6)",
		"--omp-border-muted": "#3b4252",
		"--omp-border-strong": "#4c566a",
		"--omp-success": "#a3be8c",
		"--omp-success-dim": "rgba(163, 190, 140, 0.12)",
		"--omp-error": "#bf616a",
		"--omp-error-dim": "rgba(191, 97, 106, 0.12)",
		"--omp-warning": "#ebcb8b",
		"--omp-warning-dim": "rgba(235, 203, 139, 0.12)",
		"--omp-info": "#81a1c1",
		"--omp-info-dim": "rgba(129, 161, 193, 0.12)",
		"--omp-text": "#eceff4",
		"--omp-text-secondary": "#d8dee9",
		"--omp-bg-primary": "#2e3440",
		"--omp-bg-secondary": "#343b47",
		"--omp-bg-tertiary": "#3b4252",
		"--omp-bg-elevated": "#434c5e",
		"--omp-selected-bg": "#3d4a63",
		"--omp-user-msg-bg": "#33405a",
		"--omp-user-msg-border": "#4c6186",
		"--omp-custom-msg-bg": "#3a3a52",
		"--omp-code-bg": "#272c36",
		"--omp-tool-pending-bg": "#2f3a4e",
		"--omp-tool-success-bg": "#2c4034",
		"--omp-tool-error-bg": "#422f33",
		"--omp-tool-output": "#cdd5e1",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#5c8264",
		"--omp-tool-rail-error": "#8a4f56",
		"--omp-md-heading": "#ffffff",
		"--omp-md-link": "#8fbcbb",
		"--omp-md-link-url": "#9aa5b8",
		"--omp-md-code": "#b48ead",
		"--omp-md-code-block": "#e5e9f0",
		"--omp-md-code-block-border": "#434c5e",
		"--omp-md-quote": "#c3ccd9",
		"--omp-md-quote-border": "#5a6480",
		"--omp-md-hr": "#434c5e",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#a3be8c",
		"--omp-diff-added-bg": "rgba(163, 190, 140, 0.09)",
		"--omp-diff-removed": "#bf616a",
		"--omp-diff-removed-bg": "rgba(191, 97, 106, 0.09)",
		"--omp-diff-context": "#9aa5b8",
		"--omp-syntax-comment": "#7c8698",
		"--omp-syntax-keyword": "#81a1c1",
		"--omp-syntax-function": "#88c0d0",
		"--omp-syntax-variable": "#d8dee9",
		"--omp-syntax-string": "#a3be8c",
		"--omp-syntax-number": "#b48ead",
		"--omp-syntax-type": "#8fbcbb",
		"--omp-syntax-operator": "#81a1c1",
		"--omp-syntax-punctuation": "#9aa5b8",
		"--omp-thinking-off": "#5f6b7e",
		"--omp-thinking-minimal": "#7c8698",
		"--omp-thinking-low": "#81a1c1",
		"--omp-thinking-medium": "#88c0d0",
		"--omp-thinking-high": "#b48ead",
		"--omp-thinking-xhigh": "#d8b4e2",
		"--omp-status-bg": "#272c36",
		"--omp-status-model": "#d8dee9",
		"--omp-status-path": "#a3be8c",
		"--omp-status-git-clean": "#a3be8c",
		"--omp-status-git-dirty": "#ebcb8b",
		"--omp-status-context": "#81a1c1",
		"--omp-status-spend": "#a3be8c",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#7c8698",
		"--omp-status-dim": "#5f6b7e",
		"--omp-status-text": "#eceff4",
		"--omp-status-sep": "#3f4756",
		"--omp-muted": "#aab3c5",
		"--omp-dim": "#9ea5b2",
		"--omp-link": "#8fbcbb",
		"--omp-custom-msg-label": "#88c0d0",
		"--omp-input-bg": "#333a48",
		"--omp-input-border": "#47506a",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(136, 192, 208, 0.18)",
		"--omp-btn-primary-bg": "var(--omp-accent)",
		"--omp-btn-primary-text": "#1c2430",
		"--omp-btn-secondary-bg": "#3b4252",
		"--omp-btn-secondary-text": "#eceff4",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#10141c",
		"--omp-badge-bg": "#3a4356",
		"--omp-badge-text": "#c3ccd9",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(24, 28, 36, 0.72)",
		"--omp-modal-bg": "#333a48",
		"--omp-modal-border": "#47506a",
		"--omp-toast-bg": "#333a48",
		"--omp-toast-text": "#eceff4",
		"--omp-toast-border": "#47506a",
		"--omp-progress-bg": "#3a4356",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#2b303c",
		"--omp-sidebar-item-hover": "#353c4a",
		"--omp-sidebar-item-active": "#3a4459",
		"--omp-selection-bg": "rgba(136, 192, 208, 0.26)",
		"--omp-selection-text": "#eceff4",
		"--omp-scrollbar-thumb": "#4c566a",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(136, 192, 208, 0.07)",
		"--omp-panel-bg": "#303744",
		"--omp-panel-border": "#3b4252",
		"--omp-panel-header": "#aab3c5",
		"--omp-titlebar-bg": "#2b303c",
		"--omp-titlebar-text": "#eceff4",
		"--omp-shadow-sm": "0 1px 2px rgba(0, 0, 0, 0.4)",
		"--omp-shadow-md": "0 5px 16px rgba(0, 0, 0, 0.45)",
		"--omp-shadow-lg": "0 16px 40px rgba(0, 0, 0, 0.55)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 20px var(--omp-input-glow)",
	},
};

const solarized: ThemeDefinition = {
	label: "Solarized",
	description: "Warm solarized-light with a blue accent.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#268bd2",
		"--omp-accent-bright": "#2aa198",
		"--omp-accent-dim": "rgba(38, 139, 210, 0.14)",
		"--omp-accent-glow": "rgba(38, 139, 210, 0.24)",
		"--omp-border": "#d9d2bd",
		"--omp-border-accent": "rgba(38, 139, 210, 0.55)",
		"--omp-border-muted": "#e6dfc8",
		"--omp-border-strong": "#c9c0a5",
		"--omp-success": "#859900",
		"--omp-success-dim": "rgba(133, 153, 0, 0.12)",
		"--omp-error": "#dc322f",
		"--omp-error-dim": "rgba(220, 50, 47, 0.12)",
		"--omp-warning": "#b58900",
		"--omp-warning-dim": "rgba(181, 137, 0, 0.12)",
		"--omp-info": "#2aa198",
		"--omp-info-dim": "rgba(42, 161, 152, 0.12)",
		"--omp-text": "#4d5f66",
		"--omp-text-secondary": "#586e75",
		"--omp-bg-primary": "#fdf6e3",
		"--omp-bg-secondary": "#f5efdb",
		"--omp-bg-tertiary": "#eee8d5",
		"--omp-bg-elevated": "#e6dfc8",
		"--omp-selected-bg": "#dfe6ee",
		"--omp-user-msg-bg": "#e3ecf5",
		"--omp-user-msg-border": "#b3c9e0",
		"--omp-custom-msg-bg": "#eae6d2",
		"--omp-code-bg": "#f2ecd9",
		"--omp-tool-pending-bg": "#e4ebf2",
		"--omp-tool-success-bg": "#e6ecd9",
		"--omp-tool-error-bg": "#f3e0dd",
		"--omp-tool-output": "#5a6a71",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#859900",
		"--omp-tool-rail-error": "#dc322f",
		"--omp-md-heading": "#073642",
		"--omp-md-link": "#268bd2",
		"--omp-md-link-url": "#93a1a1",
		"--omp-md-code": "#6c71c4",
		"--omp-md-code-block": "#4d5f66",
		"--omp-md-code-block-border": "#d9d2bd",
		"--omp-md-quote": "#657b83",
		"--omp-md-quote-border": "#c9c0a5",
		"--omp-md-hr": "#d9d2bd",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#859900",
		"--omp-diff-added-bg": "rgba(133, 153, 0, 0.10)",
		"--omp-diff-removed": "#dc322f",
		"--omp-diff-removed-bg": "rgba(220, 50, 47, 0.10)",
		"--omp-diff-context": "#93a1a1",
		"--omp-syntax-comment": "#93a1a1",
		"--omp-syntax-keyword": "#859900",
		"--omp-syntax-function": "#268bd2",
		"--omp-syntax-variable": "#4d5f66",
		"--omp-syntax-string": "#2aa198",
		"--omp-syntax-number": "#d33682",
		"--omp-syntax-type": "#b58900",
		"--omp-syntax-operator": "#859900",
		"--omp-syntax-punctuation": "#657b83",
		"--omp-thinking-off": "#b3b09a",
		"--omp-thinking-minimal": "#93a1a1",
		"--omp-thinking-low": "#2aa198",
		"--omp-thinking-medium": "#268bd2",
		"--omp-thinking-high": "#6c71c4",
		"--omp-thinking-xhigh": "#d33682",
		"--omp-status-bg": "#eee8d5",
		"--omp-status-model": "#586e75",
		"--omp-status-path": "#859900",
		"--omp-status-git-clean": "#859900",
		"--omp-status-git-dirty": "#b58900",
		"--omp-status-context": "#268bd2",
		"--omp-status-spend": "#2aa198",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#93a1a1",
		"--omp-status-dim": "#b3b09a",
		"--omp-status-text": "#4d5f66",
		"--omp-status-sep": "#d9d2bd",
		"--omp-muted": "#576b73",
		"--omp-dim": "#606f6f",
		"--omp-link": "#268bd2",
		"--omp-custom-msg-label": "#268bd2",
		"--omp-input-bg": "#f5efdb",
		"--omp-input-border": "#cfc6ab",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(38, 139, 210, 0.16)",
		"--omp-btn-primary-bg": "var(--omp-accent)",
		"--omp-btn-primary-text": "#042128",
		"--omp-btn-secondary-bg": "#e6dfc8",
		"--omp-btn-secondary-text": "#4d5f66",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#e6dfc8",
		"--omp-badge-text": "#586e75",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(238, 232, 213, 0.72)",
		"--omp-modal-bg": "#f5efdb",
		"--omp-modal-border": "#cfc6ab",
		"--omp-toast-bg": "#f5efdb",
		"--omp-toast-text": "#4d5f66",
		"--omp-toast-border": "#cfc6ab",
		"--omp-progress-bg": "#e6dfc8",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#f2ecd9",
		"--omp-sidebar-item-hover": "#eae4d0",
		"--omp-sidebar-item-active": "#e0d9c2",
		"--omp-selection-bg": "rgba(38, 139, 210, 0.22)",
		"--omp-selection-text": "#073642",
		"--omp-scrollbar-thumb": "#cfc6ab",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(38, 139, 210, 0.07)",
		"--omp-panel-bg": "#f2ecd9",
		"--omp-panel-border": "#e6dfc8",
		"--omp-panel-header": "#657b83",
		"--omp-titlebar-bg": "#eee8d5",
		"--omp-titlebar-text": "#4d5f66",
		"--omp-shadow-sm": "0 1px 2px rgba(101, 123, 131, 0.18)",
		"--omp-shadow-md": "0 5px 16px rgba(101, 123, 131, 0.22)",
		"--omp-shadow-lg": "0 16px 40px rgba(101, 123, 131, 0.28)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 20px var(--omp-input-glow)",
	},
};

const paper: ThemeDefinition = {
	label: "Paper",
	description: "Warm ivory pages, ink text, and a vermilion accent.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#c2410c",
		"--omp-accent-bright": "#ea580c",
		"--omp-accent-dim": "rgba(194, 65, 12, 0.08)",
		"--omp-accent-glow": "rgba(194, 65, 12, 0.16)",
		"--omp-border": "#e3ded1",
		"--omp-border-accent": "rgba(194, 65, 12, 0.38)",
		"--omp-border-muted": "#eae5d8",
		"--omp-border-strong": "#cfc8b6",
		"--omp-success": "#3f6212",
		"--omp-success-dim": "rgba(63, 98, 18, 0.10)",
		"--omp-error": "#b91c1c",
		"--omp-error-dim": "rgba(185, 28, 28, 0.08)",
		"--omp-warning": "#a16207",
		"--omp-warning-dim": "rgba(161, 98, 7, 0.09)",
		"--omp-info": "#0e7490",
		"--omp-info-dim": "rgba(14, 116, 144, 0.08)",
		"--omp-text": "#292419",
		"--omp-text-secondary": "#57503f",
		"--omp-bg-primary": "#fbf9f4",
		"--omp-bg-secondary": "#f4f1ea",
		"--omp-bg-tertiary": "#ece8de",
		"--omp-bg-elevated": "#fffefb",
		"--omp-selected-bg": "#efe9db",
		"--omp-user-msg-bg": "#f3eee3",
		"--omp-user-msg-border": "#ddd5c2",
		"--omp-custom-msg-bg": "#f0ecf8",
		"--omp-code-bg": "#f1ede3",
		"--omp-tool-pending-bg": "#f5f1e8",
		"--omp-tool-success-bg": "#e8f0dd",
		"--omp-tool-error-bg": "#f7e8e4",
		"--omp-tool-output": "#5a5344",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#7fa065",
		"--omp-tool-rail-error": "#c47d74",
		"--omp-md-heading": "#1d1a12",
		"--omp-md-link": "#c2410c",
		"--omp-md-link-url": "#9a9280",
		"--omp-md-code": "#9a3412",
		"--omp-md-code-block": "#3d382e",
		"--omp-md-code-block-border": "#e3ded1",
		"--omp-md-quote": "#6b6350",
		"--omp-md-quote-border": "#d6cfbc",
		"--omp-md-hr": "#e3ded1",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#3f6212",
		"--omp-diff-added-bg": "rgba(63, 98, 18, 0.09)",
		"--omp-diff-removed": "#b91c1c",
		"--omp-diff-removed-bg": "rgba(185, 28, 28, 0.08)",
		"--omp-diff-context": "#787060",
		"--omp-syntax-comment": "#a39e93",
		"--omp-syntax-keyword": "#9a3412",
		"--omp-syntax-function": "#0f766e",
		"--omp-syntax-variable": "#292419",
		"--omp-syntax-string": "#4d7c0f",
		"--omp-syntax-number": "#c2410c",
		"--omp-syntax-type": "#a16207",
		"--omp-syntax-operator": "#57503f",
		"--omp-syntax-punctuation": "#9a9280",
		"--omp-thinking-off": "#b5ae9c",
		"--omp-thinking-minimal": "#8b8471",
		"--omp-thinking-low": "#3d8a84",
		"--omp-thinking-medium": "#0f766e",
		"--omp-thinking-high": "#c2410c",
		"--omp-thinking-xhigh": "#ea580c",
		"--omp-status-bg": "#ece7dc",
		"--omp-status-model": "#57503f",
		"--omp-status-path": "#0e7490",
		"--omp-status-git-clean": "#3f6212",
		"--omp-status-git-dirty": "#a16207",
		"--omp-status-context": "#c2410c",
		"--omp-status-spend": "#0e7490",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#8b8471",
		"--omp-status-dim": "#b5ae9c",
		"--omp-status-text": "#292419",
		"--omp-status-sep": "#ddd6c4",
		"--omp-muted": "#787060",
		"--omp-dim": "#9a9280",
		"--omp-link": "#c2410c",
		"--omp-custom-msg-label": "#c2410c",
		"--omp-input-bg": "#fffefb",
		"--omp-input-border": "#d8d2c0",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(194, 65, 12, 0.12)",
		"--omp-btn-primary-bg": "#c2410c",
		"--omp-btn-primary-text": "#ffffff",
		"--omp-btn-secondary-bg": "#ece8de",
		"--omp-btn-secondary-text": "#292419",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#ece8de",
		"--omp-badge-text": "#6b6350",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(47, 40, 28, 0.32)",
		"--omp-modal-bg": "#fffefb",
		"--omp-modal-border": "#e3ded1",
		"--omp-toast-bg": "#fffefb",
		"--omp-toast-text": "#292419",
		"--omp-toast-border": "#e3ded1",
		"--omp-progress-bg": "#e6e0d2",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#f4f1ea",
		"--omp-sidebar-item-hover": "#ece8dd",
		"--omp-sidebar-item-active": "#e6e0d1",
		"--omp-selection-bg": "rgba(194, 65, 12, 0.14)",
		"--omp-selection-text": "#1d1a12",
		"--omp-scrollbar-thumb": "#c9c2ae",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(194, 65, 12, 0.05)",
		"--omp-panel-bg": "#f4f1ea",
		"--omp-panel-border": "#e8e3d6",
		"--omp-panel-header": "#787060",
		"--omp-titlebar-bg": "#fbf9f4",
		"--omp-titlebar-text": "#292419",
		"--omp-shadow-sm": "0 1px 2px rgba(61, 50, 30, 0.07)",
		"--omp-shadow-md": "0 4px 14px rgba(61, 50, 30, 0.09)",
		"--omp-shadow-lg": "0 14px 38px rgba(61, 50, 30, 0.13)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 14px var(--omp-input-glow)",
	},
};

const dawn: ThemeDefinition = {
	label: "Rosé Pine Dawn",
	description: "Soft warm pastels — pine, rose, and gold on cream.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#286983",
		"--omp-accent-bright": "#56949f",
		"--omp-accent-dim": "rgba(40, 105, 131, 0.09)",
		"--omp-accent-glow": "rgba(40, 105, 131, 0.16)",
		"--omp-border": "#eaddd4",
		"--omp-border-accent": "rgba(40, 105, 131, 0.35)",
		"--omp-border-muted": "#f0e6dd",
		"--omp-border-strong": "#d9c9bb",
		"--omp-success": "#4e8c68",
		"--omp-success-dim": "rgba(78, 140, 104, 0.10)",
		"--omp-error": "#b4637a",
		"--omp-error-dim": "rgba(180, 99, 122, 0.08)",
		"--omp-warning": "#d98a1f",
		"--omp-warning-dim": "rgba(234, 157, 52, 0.14)",
		"--omp-info": "#56949f",
		"--omp-info-dim": "rgba(86, 148, 159, 0.12)",
		"--omp-text": "#575279",
		"--omp-text-secondary": "#797593",
		"--omp-bg-primary": "#faf4ed",
		"--omp-bg-secondary": "#fffaf3",
		"--omp-bg-tertiary": "#f2e9e1",
		"--omp-bg-elevated": "#fffaf3",
		"--omp-selected-bg": "#f0e4d8",
		"--omp-user-msg-bg": "#f6ece1",
		"--omp-user-msg-border": "#e5d4c4",
		"--omp-custom-msg-bg": "#f2e9f2",
		"--omp-code-bg": "#f6ede4",
		"--omp-tool-pending-bg": "#f7efe6",
		"--omp-tool-success-bg": "#e8f1ea",
		"--omp-tool-error-bg": "#f7e6e6",
		"--omp-tool-output": "#6e6a86",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#7aa48f",
		"--omp-tool-rail-error": "#c98a94",
		"--omp-md-heading": "#46415f",
		"--omp-md-link": "#286983",
		"--omp-md-link-url": "#9893a5",
		"--omp-md-code": "#b4637a",
		"--omp-md-code-block": "#575279",
		"--omp-md-code-block-border": "#eaddd4",
		"--omp-md-quote": "#797593",
		"--omp-md-quote-border": "#d9c9bb",
		"--omp-md-hr": "#eaddd4",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#4e8c68",
		"--omp-diff-added-bg": "rgba(78, 140, 104, 0.08)",
		"--omp-diff-removed": "#b4637a",
		"--omp-diff-removed-bg": "rgba(180, 99, 122, 0.08)",
		"--omp-diff-context": "#9893a5",
		"--omp-syntax-comment": "#9893a5",
		"--omp-syntax-keyword": "#286983",
		"--omp-syntax-function": "#b4637a",
		"--omp-syntax-variable": "#575279",
		"--omp-syntax-string": "#b97c15",
		"--omp-syntax-number": "#286983",
		"--omp-syntax-type": "#3e8a96",
		"--omp-syntax-operator": "#797593",
		"--omp-syntax-punctuation": "#9893a5",
		"--omp-thinking-off": "#b3aec2",
		"--omp-thinking-minimal": "#918ba6",
		"--omp-thinking-low": "#56949f",
		"--omp-thinking-medium": "#286983",
		"--omp-thinking-high": "#b4637a",
		"--omp-thinking-xhigh": "#c96f68",
		"--omp-status-bg": "#f2e9e1",
		"--omp-status-model": "#797593",
		"--omp-status-path": "#56949f",
		"--omp-status-git-clean": "#4e8c68",
		"--omp-status-git-dirty": "#d98a1f",
		"--omp-status-context": "#286983",
		"--omp-status-spend": "#56949f",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#918ba6",
		"--omp-status-dim": "#c4bdcb",
		"--omp-status-text": "#575279",
		"--omp-status-sep": "#e5d6cb",
		"--omp-muted": "#797593",
		"--omp-dim": "#9893a5",
		"--omp-link": "#286983",
		"--omp-custom-msg-label": "#286983",
		"--omp-input-bg": "#fffaf3",
		"--omp-input-border": "#e2d5c8",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(40, 105, 131, 0.12)",
		"--omp-btn-primary-bg": "#286983",
		"--omp-btn-primary-text": "#ffffff",
		"--omp-btn-secondary-bg": "#f2e9e1",
		"--omp-btn-secondary-text": "#575279",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#f2e9e1",
		"--omp-badge-text": "#797593",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(70, 60, 75, 0.30)",
		"--omp-modal-bg": "#fffaf3",
		"--omp-modal-border": "#eaddd4",
		"--omp-toast-bg": "#fffaf3",
		"--omp-toast-text": "#575279",
		"--omp-toast-border": "#eaddd4",
		"--omp-progress-bg": "#eadfd3",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#fbf5ef",
		"--omp-sidebar-item-hover": "#f2e9e1",
		"--omp-sidebar-item-active": "#efe2d6",
		"--omp-selection-bg": "rgba(40, 105, 131, 0.14)",
		"--omp-selection-text": "#46415f",
		"--omp-scrollbar-thumb": "#d4c3b4",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(40, 105, 131, 0.05)",
		"--omp-panel-bg": "#fbf5ef",
		"--omp-panel-border": "#eadfd5",
		"--omp-panel-header": "#797593",
		"--omp-titlebar-bg": "#faf4ed",
		"--omp-titlebar-text": "#575279",
		"--omp-shadow-sm": "0 1px 2px rgba(90, 70, 60, 0.07)",
		"--omp-shadow-md": "0 4px 14px rgba(90, 70, 60, 0.09)",
		"--omp-shadow-lg": "0 14px 38px rgba(90, 70, 60, 0.13)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 14px var(--omp-input-glow)",
	},
};

const latte: ThemeDefinition = {
	label: "Catppuccin Latte",
	description: "Soothing pastel palette with a bright blue accent.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#1e66f5",
		"--omp-accent-bright": "#3f7cf6",
		"--omp-accent-dim": "rgba(30, 102, 245, 0.08)",
		"--omp-accent-glow": "rgba(30, 102, 245, 0.15)",
		"--omp-border": "#ccd0da",
		"--omp-border-accent": "rgba(30, 102, 245, 0.35)",
		"--omp-border-muted": "#d8dce4",
		"--omp-border-strong": "#acb0be",
		"--omp-success": "#40a02b",
		"--omp-success-dim": "rgba(64, 160, 43, 0.09)",
		"--omp-error": "#d20f39",
		"--omp-error-dim": "rgba(210, 15, 57, 0.08)",
		"--omp-warning": "#df8e1d",
		"--omp-warning-dim": "rgba(223, 142, 29, 0.12)",
		"--omp-info": "#04a5e5",
		"--omp-info-dim": "rgba(4, 165, 229, 0.10)",
		"--omp-text": "#4c4f69",
		"--omp-text-secondary": "#5c5f77",
		"--omp-bg-primary": "#eff1f5",
		"--omp-bg-secondary": "#e6e9ef",
		"--omp-bg-tertiary": "#dce0e8",
		"--omp-bg-elevated": "#ffffff",
		"--omp-selected-bg": "#e2e6ee",
		"--omp-user-msg-bg": "#e4e9f2",
		"--omp-user-msg-border": "#cbd3e2",
		"--omp-custom-msg-bg": "#eee9f7",
		"--omp-code-bg": "#e9ecf2",
		"--omp-tool-pending-bg": "#eceff5",
		"--omp-tool-success-bg": "#e3f0e2",
		"--omp-tool-error-bg": "#f6e2e6",
		"--omp-tool-output": "#5c5f77",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#74b36a",
		"--omp-tool-rail-error": "#de7a8d",
		"--omp-md-heading": "#3b3e52",
		"--omp-md-link": "#1e66f5",
		"--omp-md-link-url": "#9ca0b0",
		"--omp-md-code": "#fe640b",
		"--omp-md-code-block": "#4c4f69",
		"--omp-md-code-block-border": "#ccd0da",
		"--omp-md-quote": "#6c6f85",
		"--omp-md-quote-border": "#bcc0cc",
		"--omp-md-hr": "#ccd0da",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#40a02b",
		"--omp-diff-added-bg": "rgba(64, 160, 43, 0.08)",
		"--omp-diff-removed": "#d20f39",
		"--omp-diff-removed-bg": "rgba(210, 15, 57, 0.07)",
		"--omp-diff-context": "#8c8fa1",
		"--omp-syntax-comment": "#9ca0b0",
		"--omp-syntax-keyword": "#1e66f5",
		"--omp-syntax-function": "#1e66f5",
		"--omp-syntax-variable": "#4c4f69",
		"--omp-syntax-string": "#40a02b",
		"--omp-syntax-number": "#fe640b",
		"--omp-syntax-type": "#df8e1d",
		"--omp-syntax-operator": "#179299",
		"--omp-syntax-punctuation": "#6c6f85",
		"--omp-thinking-off": "#b8bcc8",
		"--omp-thinking-minimal": "#9396a8",
		"--omp-thinking-low": "#179299",
		"--omp-thinking-medium": "#1e66f5",
		"--omp-thinking-high": "#8839ef",
		"--omp-thinking-xhigh": "#d14fb0",
		"--omp-status-bg": "#e6e9ef",
		"--omp-status-model": "#5c5f77",
		"--omp-status-path": "#179299",
		"--omp-status-git-clean": "#40a02b",
		"--omp-status-git-dirty": "#df8e1d",
		"--omp-status-context": "#1e66f5",
		"--omp-status-spend": "#179299",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#9396a8",
		"--omp-status-dim": "#b8bcc8",
		"--omp-status-text": "#4c4f69",
		"--omp-status-sep": "#d5dae3",
		"--omp-muted": "#6c6f85",
		"--omp-dim": "#9ca0b0",
		"--omp-link": "#1e66f5",
		"--omp-custom-msg-label": "#1e66f5",
		"--omp-input-bg": "#ffffff",
		"--omp-input-border": "#c3c9d4",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(30, 102, 245, 0.12)",
		"--omp-btn-primary-bg": "#1e66f5",
		"--omp-btn-primary-text": "#ffffff",
		"--omp-btn-secondary-bg": "#e2e6ee",
		"--omp-btn-secondary-text": "#4c4f69",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#e2e6ee",
		"--omp-badge-text": "#5c5f77",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(76, 79, 105, 0.30)",
		"--omp-modal-bg": "#ffffff",
		"--omp-modal-border": "#ccd0da",
		"--omp-toast-bg": "#ffffff",
		"--omp-toast-text": "#4c4f69",
		"--omp-toast-border": "#ccd0da",
		"--omp-progress-bg": "#dde1ea",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#e6e9ef",
		"--omp-sidebar-item-hover": "#dee2ea",
		"--omp-sidebar-item-active": "#dfe4ee",
		"--omp-selection-bg": "rgba(30, 102, 245, 0.14)",
		"--omp-selection-text": "#3b3e52",
		"--omp-scrollbar-thumb": "#b4b9c6",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(30, 102, 245, 0.05)",
		"--omp-panel-bg": "#e6e9ef",
		"--omp-panel-border": "#d8dce4",
		"--omp-panel-header": "#6c6f85",
		"--omp-titlebar-bg": "#e9ecf1",
		"--omp-titlebar-text": "#4c4f69",
		"--omp-shadow-sm": "0 1px 2px rgba(76, 79, 105, 0.07)",
		"--omp-shadow-md": "0 4px 14px rgba(76, 79, 105, 0.09)",
		"--omp-shadow-lg": "0 14px 38px rgba(76, 79, 105, 0.13)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 14px var(--omp-input-glow)",
	},
};

const gruvbox: ThemeDefinition = {
	label: "Gruvbox Light",
	description: "Retro groove: warm cream with earthy, high-contrast colors.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#af3a03",
		"--omp-accent-bright": "#cc4d0a",
		"--omp-accent-dim": "rgba(175, 58, 3, 0.09)",
		"--omp-accent-glow": "rgba(175, 58, 3, 0.15)",
		"--omp-border": "#d5c4a1",
		"--omp-border-accent": "rgba(175, 58, 3, 0.38)",
		"--omp-border-muted": "#e2d4ae",
		"--omp-border-strong": "#bdae93",
		"--omp-success": "#79740e",
		"--omp-success-dim": "rgba(121, 116, 14, 0.10)",
		"--omp-error": "#9d0006",
		"--omp-error-dim": "rgba(157, 0, 6, 0.07)",
		"--omp-warning": "#b57614",
		"--omp-warning-dim": "rgba(181, 118, 20, 0.12)",
		"--omp-info": "#076678",
		"--omp-info-dim": "rgba(7, 102, 120, 0.09)",
		"--omp-text": "#3c3836",
		"--omp-text-secondary": "#504945",
		"--omp-bg-primary": "#fbf1c7",
		"--omp-bg-secondary": "#f2e5bc",
		"--omp-bg-tertiary": "#ebdbb2",
		"--omp-bg-elevated": "#fdf6d9",
		"--omp-selected-bg": "#eddcae",
		"--omp-user-msg-bg": "#f0e2b6",
		"--omp-user-msg-border": "#dccb9d",
		"--omp-custom-msg-bg": "#efe0c9",
		"--omp-code-bg": "#f2e5bc",
		"--omp-tool-pending-bg": "#f4e9c2",
		"--omp-tool-success-bg": "#e5e7c0",
		"--omp-tool-error-bg": "#f3ddc6",
		"--omp-tool-output": "#5a5348",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#8f9448",
		"--omp-tool-rail-error": "#b0685b",
		"--omp-md-heading": "#282828",
		"--omp-md-link": "#076678",
		"--omp-md-link-url": "#928374",
		"--omp-md-code": "#af3a03",
		"--omp-md-code-block": "#3c3836",
		"--omp-md-code-block-border": "#d5c4a1",
		"--omp-md-quote": "#665c54",
		"--omp-md-quote-border": "#bdae93",
		"--omp-md-hr": "#d5c4a1",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#79740e",
		"--omp-diff-added-bg": "rgba(121, 116, 14, 0.10)",
		"--omp-diff-removed": "#9d0006",
		"--omp-diff-removed-bg": "rgba(157, 0, 6, 0.08)",
		"--omp-diff-context": "#928374",
		"--omp-syntax-comment": "#928374",
		"--omp-syntax-keyword": "#9d0006",
		"--omp-syntax-function": "#076678",
		"--omp-syntax-variable": "#3c3836",
		"--omp-syntax-string": "#79740e",
		"--omp-syntax-number": "#8f3f71",
		"--omp-syntax-type": "#b57614",
		"--omp-syntax-operator": "#504945",
		"--omp-syntax-punctuation": "#7c6f64",
		"--omp-thinking-off": "#b3a68d",
		"--omp-thinking-minimal": "#8b7f68",
		"--omp-thinking-low": "#427b58",
		"--omp-thinking-medium": "#076678",
		"--omp-thinking-high": "#af3a03",
		"--omp-thinking-xhigh": "#c7450b",
		"--omp-status-bg": "#ebdbb2",
		"--omp-status-model": "#504945",
		"--omp-status-path": "#427b58",
		"--omp-status-git-clean": "#79740e",
		"--omp-status-git-dirty": "#b57614",
		"--omp-status-context": "#076678",
		"--omp-status-spend": "#427b58",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#8b7f68",
		"--omp-status-dim": "#b3a68d",
		"--omp-status-text": "#3c3836",
		"--omp-status-sep": "#dccfa9",
		"--omp-muted": "#665c54",
		"--omp-dim": "#928374",
		"--omp-link": "#076678",
		"--omp-custom-msg-label": "#af3a03",
		"--omp-input-bg": "#fdf6d9",
		"--omp-input-border": "#cbb98f",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(175, 58, 3, 0.14)",
		"--omp-btn-primary-bg": "#3c3836",
		"--omp-btn-primary-text": "#fbf1c7",
		"--omp-btn-secondary-bg": "#ebdbb2",
		"--omp-btn-secondary-text": "#3c3836",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#fbf1c7",
		"--omp-badge-bg": "#ebdbb2",
		"--omp-badge-text": "#665c54",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(60, 56, 54, 0.30)",
		"--omp-modal-bg": "#fdf6d9",
		"--omp-modal-border": "#d5c4a1",
		"--omp-toast-bg": "#fdf6d9",
		"--omp-toast-text": "#3c3836",
		"--omp-toast-border": "#d5c4a1",
		"--omp-progress-bg": "#e2d4ae",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#f2e5bc",
		"--omp-sidebar-item-hover": "#ece0b4",
		"--omp-sidebar-item-active": "#e7d9a8",
		"--omp-selection-bg": "rgba(175, 58, 3, 0.14)",
		"--omp-selection-text": "#282828",
		"--omp-scrollbar-thumb": "#bdae93",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(175, 58, 3, 0.05)",
		"--omp-panel-bg": "#f2e5bc",
		"--omp-panel-border": "#ddcfa9",
		"--omp-panel-header": "#665c54",
		"--omp-titlebar-bg": "#fbf1c7",
		"--omp-titlebar-text": "#3c3836",
		"--omp-shadow-sm": "0 1px 2px rgba(60, 50, 20, 0.08)",
		"--omp-shadow-md": "0 4px 14px rgba(60, 50, 20, 0.10)",
		"--omp-shadow-lg": "0 14px 38px rgba(60, 50, 20, 0.14)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 14px var(--omp-input-glow)",
	},
};

const frost: ThemeDefinition = {
	label: "Frost",
	description: "Crisp neutral cool light with a deep-blue accent.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#2563eb",
		"--omp-accent-bright": "#3b82f6",
		"--omp-accent-dim": "rgba(37, 99, 235, 0.08)",
		"--omp-accent-glow": "rgba(37, 99, 235, 0.15)",
		"--omp-border": "#dbe3ec",
		"--omp-border-accent": "rgba(37, 99, 235, 0.35)",
		"--omp-border-muted": "#e4eaf1",
		"--omp-border-strong": "#c3cfdd",
		"--omp-success": "#059669",
		"--omp-success-dim": "rgba(5, 150, 105, 0.09)",
		"--omp-error": "#dc2626",
		"--omp-error-dim": "rgba(220, 38, 38, 0.08)",
		"--omp-warning": "#d97706",
		"--omp-warning-dim": "rgba(217, 119, 6, 0.10)",
		"--omp-info": "#0284c7",
		"--omp-info-dim": "rgba(2, 132, 199, 0.09)",
		"--omp-text": "#0f172a",
		"--omp-text-secondary": "#334155",
		"--omp-bg-primary": "#f8fafc",
		"--omp-bg-secondary": "#f1f5f9",
		"--omp-bg-tertiary": "#e7edf3",
		"--omp-bg-elevated": "#ffffff",
		"--omp-selected-bg": "#e3eaf3",
		"--omp-user-msg-bg": "#e8eef6",
		"--omp-user-msg-border": "#cfdae8",
		"--omp-custom-msg-bg": "#eeedf8",
		"--omp-code-bg": "#eef3f8",
		"--omp-tool-pending-bg": "#eff4f9",
		"--omp-tool-success-bg": "#e2f1ea",
		"--omp-tool-error-bg": "#f8e6e6",
		"--omp-tool-output": "#475569",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#63a583",
		"--omp-tool-rail-error": "#d18a8a",
		"--omp-md-heading": "#0b1220",
		"--omp-md-link": "#2563eb",
		"--omp-md-link-url": "#94a3b8",
		"--omp-md-code": "#b45309",
		"--omp-md-code-block": "#1f2937",
		"--omp-md-code-block-border": "#dbe3ec",
		"--omp-md-quote": "#64748b",
		"--omp-md-quote-border": "#c3cfdd",
		"--omp-md-hr": "#dbe3ec",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#059669",
		"--omp-diff-added-bg": "rgba(5, 150, 105, 0.08)",
		"--omp-diff-removed": "#dc2626",
		"--omp-diff-removed-bg": "rgba(220, 38, 38, 0.07)",
		"--omp-diff-context": "#94a3b8",
		"--omp-syntax-comment": "#94a3b8",
		"--omp-syntax-keyword": "#2563eb",
		"--omp-syntax-function": "#0369a1",
		"--omp-syntax-variable": "#0f172a",
		"--omp-syntax-string": "#047857",
		"--omp-syntax-number": "#b45309",
		"--omp-syntax-type": "#0e7490",
		"--omp-syntax-operator": "#334155",
		"--omp-syntax-punctuation": "#64748b",
		"--omp-thinking-off": "#b0bac7",
		"--omp-thinking-minimal": "#8b98a8",
		"--omp-thinking-low": "#0284c7",
		"--omp-thinking-medium": "#2563eb",
		"--omp-thinking-high": "#1d4ed8",
		"--omp-thinking-xhigh": "#1e3a8a",
		"--omp-status-bg": "#e7edf3",
		"--omp-status-model": "#57503f",
		"--omp-status-path": "#0e7490",
		"--omp-status-git-clean": "#059669",
		"--omp-status-git-dirty": "#d97706",
		"--omp-status-context": "#2563eb",
		"--omp-status-spend": "#0e7490",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#8b98a8",
		"--omp-status-dim": "#b0bac7",
		"--omp-status-text": "#0f172a",
		"--omp-status-sep": "#dbe3ec",
		"--omp-muted": "#64748b",
		"--omp-dim": "#94a3b8",
		"--omp-link": "#2563eb",
		"--omp-custom-msg-label": "#2563eb",
		"--omp-input-bg": "#ffffff",
		"--omp-input-border": "#cbd5e1",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(37, 99, 235, 0.12)",
		"--omp-btn-primary-bg": "#2563eb",
		"--omp-btn-primary-text": "#ffffff",
		"--omp-btn-secondary-bg": "#e7edf3",
		"--omp-btn-secondary-text": "#0f172a",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#e7edf3",
		"--omp-badge-text": "#475569",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(15, 23, 42, 0.32)",
		"--omp-modal-bg": "#ffffff",
		"--omp-modal-border": "#dbe3ec",
		"--omp-toast-bg": "#ffffff",
		"--omp-toast-text": "#0f172a",
		"--omp-toast-border": "#dbe3ec",
		"--omp-progress-bg": "#e2e8f0",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#f1f5f9",
		"--omp-sidebar-item-hover": "#e9eff5",
		"--omp-sidebar-item-active": "#e3eaf3",
		"--omp-selection-bg": "rgba(37, 99, 235, 0.14)",
		"--omp-selection-text": "#0b1220",
		"--omp-scrollbar-thumb": "#b9c5d3",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(37, 99, 235, 0.05)",
		"--omp-panel-bg": "#f1f5f9",
		"--omp-panel-border": "#e1e8f0",
		"--omp-panel-header": "#64748b",
		"--omp-titlebar-bg": "#f8fafc",
		"--omp-titlebar-text": "#0f172a",
		"--omp-shadow-sm": "0 1px 2px rgba(15, 23, 42, 0.06)",
		"--omp-shadow-md": "0 4px 14px rgba(15, 23, 42, 0.08)",
		"--omp-shadow-lg": "0 14px 38px rgba(15, 23, 42, 0.12)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 14px var(--omp-input-glow)",
	},
};

const matcha: ThemeDefinition = {
	label: "Matcha",
	description: "Soft green-cream surfaces with a calm sage accent.",
	scheme: "light",
	tokens: {
		"--omp-accent": "#4d7c0f",
		"--omp-accent-bright": "#65a30d",
		"--omp-accent-dim": "rgba(77, 124, 15, 0.09)",
		"--omp-accent-glow": "rgba(77, 124, 15, 0.16)",
		"--omp-border": "#dde4cd",
		"--omp-border-accent": "rgba(77, 124, 15, 0.36)",
		"--omp-border-muted": "#e5ebd8",
		"--omp-border-strong": "#c6d0ae",
		"--omp-success": "#15803d",
		"--omp-success-dim": "rgba(21, 128, 61, 0.10)",
		"--omp-error": "#b91c1c",
		"--omp-error-dim": "rgba(185, 28, 28, 0.08)",
		"--omp-warning": "#a16207",
		"--omp-warning-dim": "rgba(161, 98, 7, 0.10)",
		"--omp-info": "#0f766e",
		"--omp-info-dim": "rgba(15, 118, 110, 0.09)",
		"--omp-text": "#33392b",
		"--omp-text-secondary": "#555e47",
		"--omp-bg-primary": "#f6f8f1",
		"--omp-bg-secondary": "#eef2e5",
		"--omp-bg-tertiary": "#e4ead6",
		"--omp-bg-elevated": "#fcfdf8",
		"--omp-selected-bg": "#e6ecd4",
		"--omp-user-msg-bg": "#e9efdb",
		"--omp-user-msg-border": "#d3dcbc",
		"--omp-custom-msg-bg": "#f1ecdd",
		"--omp-code-bg": "#edf2e2",
		"--omp-tool-pending-bg": "#f0f4e5",
		"--omp-tool-success-bg": "#e3efdb",
		"--omp-tool-error-bg": "#f6e7e0",
		"--omp-tool-output": "#5a634d",
		"--omp-tool-rail-running": "var(--omp-accent)",
		"--omp-tool-rail-done": "#8aa86e",
		"--omp-tool-rail-error": "#c98a7a",
		"--omp-md-heading": "#2b3022",
		"--omp-md-link": "#4d7c0f",
		"--omp-md-link-url": "#9aa389",
		"--omp-md-code": "#9a3412",
		"--omp-md-code-block": "#3a4030",
		"--omp-md-code-block-border": "#dde4cd",
		"--omp-md-quote": "#707a5e",
		"--omp-md-quote-border": "#c6d0ae",
		"--omp-md-hr": "#dde4cd",
		"--omp-md-list-bullet": "var(--omp-accent)",
		"--omp-diff-added": "#15803d",
		"--omp-diff-added-bg": "rgba(21, 128, 61, 0.09)",
		"--omp-diff-removed": "#b91c1c",
		"--omp-diff-removed-bg": "rgba(185, 28, 28, 0.08)",
		"--omp-diff-context": "#8b937a",
		"--omp-syntax-comment": "#9aa389",
		"--omp-syntax-keyword": "#7c2d12",
		"--omp-syntax-function": "#0f766e",
		"--omp-syntax-variable": "#33392b",
		"--omp-syntax-string": "#4d7c0f",
		"--omp-syntax-number": "#a16207",
		"--omp-syntax-type": "#b45309",
		"--omp-syntax-operator": "#555e47",
		"--omp-syntax-punctuation": "#8b937a",
		"--omp-thinking-off": "#b6bda6",
		"--omp-thinking-minimal": "#8f987c",
		"--omp-thinking-low": "#0f766e",
		"--omp-thinking-medium": "#4d7c0f",
		"--omp-thinking-high": "#9a3412",
		"--omp-thinking-xhigh": "#c2410c",
		"--omp-status-bg": "#e4ead6",
		"--omp-status-model": "#57503f",
		"--omp-status-path": "#0f766e",
		"--omp-status-git-clean": "#15803d",
		"--omp-status-git-dirty": "#a16207",
		"--omp-status-context": "#4d7c0f",
		"--omp-status-spend": "#0f766e",
		"--omp-status-subagents": "var(--omp-accent)",
		"--omp-status-muted": "#8f987c",
		"--omp-status-dim": "#b6bda6",
		"--omp-status-text": "#33392b",
		"--omp-status-sep": "#dbe2c8",
		"--omp-muted": "#707a5e",
		"--omp-dim": "#9aa389",
		"--omp-link": "#4d7c0f",
		"--omp-custom-msg-label": "#9a3412",
		"--omp-input-bg": "#fcfdf8",
		"--omp-input-border": "#cdd6b4",
		"--omp-input-focus-border": "var(--omp-accent)",
		"--omp-input-glow": "rgba(77, 124, 15, 0.13)",
		"--omp-btn-primary-bg": "#4d7c0f",
		"--omp-btn-primary-text": "#ffffff",
		"--omp-btn-secondary-bg": "#e4ead6",
		"--omp-btn-secondary-text": "#33392b",
		"--omp-btn-danger-bg": "var(--omp-error)",
		"--omp-btn-danger-text": "#ffffff",
		"--omp-badge-bg": "#e4ead6",
		"--omp-badge-text": "#5a634d",
		"--omp-badge-accent": "var(--omp-accent)",
		"--omp-overlay-bg": "rgba(51, 57, 43, 0.30)",
		"--omp-modal-bg": "#fcfdf8",
		"--omp-modal-border": "#dde4cd",
		"--omp-toast-bg": "#fcfdf8",
		"--omp-toast-text": "#33392b",
		"--omp-toast-border": "#dde4cd",
		"--omp-progress-bg": "#e0e6cf",
		"--omp-progress-fill": "var(--omp-accent)",
		"--omp-sidebar-bg": "#eef2e5",
		"--omp-sidebar-item-hover": "#e6ecda",
		"--omp-sidebar-item-active": "#e0e7cd",
		"--omp-selection-bg": "rgba(77, 124, 15, 0.14)",
		"--omp-selection-text": "#2b3022",
		"--omp-scrollbar-thumb": "#c2cdaa",
		"--omp-scrollbar-track": "transparent",
		"--omp-streaming-cursor": "var(--omp-accent)",
		"--omp-streaming-highlight": "rgba(77, 124, 15, 0.05)",
		"--omp-panel-bg": "#eef2e5",
		"--omp-panel-border": "#e1e7d2",
		"--omp-panel-header": "#707a5e",
		"--omp-titlebar-bg": "#f6f8f1",
		"--omp-titlebar-text": "#33392b",
		"--omp-shadow-sm": "0 1px 2px rgba(51, 57, 43, 0.07)",
		"--omp-shadow-md": "0 4px 14px rgba(51, 57, 43, 0.09)",
		"--omp-shadow-lg": "0 14px 38px rgba(51, 57, 43, 0.13)",
		"--omp-shadow-glow": "0 0 0 1px var(--omp-border-accent), 0 0 14px var(--omp-input-glow)",
	},
};

export const THEMES = {
	dark,
	titanium,
	nord,
	light,
	solarized,
	paper,
	dawn,
	latte,
	gruvbox,
	frost,
	matcha,
} as const satisfies Record<string, ThemeDefinition>;

export type ThemeName = keyof typeof THEMES;

/** A picker selection: a named theme, or "system" to follow the OS. */
export type ThemeSelection = ThemeName | "system";

export function isThemeSelection(value: unknown): value is ThemeSelection {
	return typeof value === "string" && (value === "system" || value in THEMES);
}

/** The theme actually shown for a selection ("system" resolves via the OS). */
export function resolveThemeSelection(selection: ThemeSelection): ThemeDefinition {
	return THEMES[selection === "system" ? resolveTheme("system") : selection];
}

/**
 * Inline tokens most recently written by applyThemeByName for a named theme;
 * null while the "system" selection is stylesheet-driven. The agent theme
 * overlay (bottom of this file) restores these when an override goes away.
 */
let baseThemeTokens: ThemeTokens | null = null;

/**
 * Applies a theme selection live: flips `data-theme` + the color-scheme meta
 * to the theme's base scheme, then writes every token inline on <html>.
 * "system" stays purely stylesheet-driven (dark/light resolve per the OS
 * media query, and lib/theme's watcher re-applies on OS changes). Persists
 * the selection under the `themeName` pref and mirrors the base scheme (or
 * "system") into the legacy `theme` pref so older boot paths stay coherent.
 * Pass `{ persist: false }` for ephemeral previews (settings-window theme
 * browsing) so the user's stored selection is left untouched.
 */
export function applyThemeByName(selection: ThemeSelection, opts: { persist?: boolean } = {}): void {
	const { persist = true } = opts;
	const legacyTheme = selection === "system" ? "system" : THEMES[selection].scheme;
	if (selection !== "system") {
		const theme = THEMES[selection];
		applyTheme(theme.scheme);
		const style = document.documentElement.style;
		for (const key of THEME_TOKEN_KEYS) style.setProperty(key, theme.tokens[key]);
		baseThemeTokens = theme.tokens;
		markCustomThemeTokens(theme.scheme);
	} else {
		baseThemeTokens = null;
		applyTheme("system");
	}
	if (persist) {
		void window.omp.prefs.set("themeName", selection);
		void window.omp.prefs.set("theme", legacyTheme);
	}
}

/**
 * Reads the persisted selection: the `themeName` pref first, then the legacy
 * `theme` pref (dark/light/system written by older builds and the settings
 * window), falling back to "light" — the historical store default.
 */
export async function getPersistedThemeSelection(): Promise<ThemeSelection> {
	try {
		const named = await window.omp.prefs.get("themeName");
		if (isThemeSelection(named)) return named;
		const legacy = await window.omp.prefs.get("theme");
		if (isThemeSelection(legacy)) return legacy;
	} catch {
		// prefs IPC unavailable (tests, storybook) — use the default.
	}
	return "light";
}

/**
 * Resolves one level of `var(--omp-…)` indirection for swatch previews.
 * Values that are not a bare var() reference are returned unchanged.
 */
export function resolveTokenColor(theme: ThemeDefinition, key: ThemeTokenKey): string {
	const value = theme.tokens[key];
	const match = /^var\((--omp-[a-z-]+)\)$/.exec(value);
	if (!match) return value;
	return theme.tokens[match[1] as ThemeTokenKey] ?? value;
}

// ============================================================================
// Agent theme overlay (theme.dark / theme.light)
// ============================================================================

/**
 * TUI theme token → GUI `--omp-*` custom property. Only tokens with an exact
 * counterpart on both sides are mapped; everything else stays owned by the
 * active GUI named theme. TUI tokens deliberately left unmapped (no verified
 * GUI semantic — do not approximate):
 * - thinkingText, toolTitle, userMessageText, customMessageText: the GUI has
 *   no dedicated foreground tokens for these surfaces.
 * - thinkingMax: the GUI thinking ramp ends at --omp-thinking-xhigh.
 * - bashMode, pythonMode: TUI REPL prompt-mode accents with no GUI counterpart.
 * - statusLineStaged / statusLineDirty / statusLineUntracked /
 *   statusLineOutput / statusLineCost: TUI status-line counters the GUI
 *   footer does not tokenize.
 * - "link": an undeclared colors key some theme files carry; it is not part
 *   of the TUI theme schema (ThemeColor), so its role is unverifiable.
 *   mdLink already covers --omp-md-link.
 */
/**
 * TUI theme overlay may retint transcript internals only. Chrome tokens
 * (accent, sidebar, titlebar, buttons, inputs, status-line) stay with the
 * named GUI theme so the app identity cannot be swapped by sidecar themes.
 */
export const TRANSCRIPT_OVERLAY_VARS: Record<string, ThemeTokenKey> = {
	userMessageBg: "--omp-user-msg-bg",
	customMessageBg: "--omp-custom-msg-bg",
	customMessageLabel: "--omp-custom-msg-label",
	toolPendingBg: "--omp-tool-pending-bg",
	toolSuccessBg: "--omp-tool-success-bg",
	toolErrorBg: "--omp-tool-error-bg",
	toolOutput: "--omp-tool-output",
	mdHeading: "--omp-md-heading",
	mdLink: "--omp-md-link",
	mdLinkUrl: "--omp-md-link-url",
	mdCode: "--omp-md-code",
	mdCodeBlock: "--omp-md-code-block",
	mdCodeBlockBorder: "--omp-md-code-block-border",
	mdQuote: "--omp-md-quote",
	mdQuoteBorder: "--omp-md-quote-border",
	mdHr: "--omp-md-hr",
	mdListBullet: "--omp-md-list-bullet",
	toolDiffAdded: "--omp-diff-added",
	toolDiffRemoved: "--omp-diff-removed",
	toolDiffContext: "--omp-diff-context",
	syntaxComment: "--omp-syntax-comment",
	syntaxKeyword: "--omp-syntax-keyword",
	syntaxFunction: "--omp-syntax-function",
	syntaxVariable: "--omp-syntax-variable",
	syntaxString: "--omp-syntax-string",
	syntaxNumber: "--omp-syntax-number",
	syntaxType: "--omp-syntax-type",
	syntaxOperator: "--omp-syntax-operator",
	syntaxPunctuation: "--omp-syntax-punctuation",
	thinkingOff: "--omp-thinking-off",
	thinkingMinimal: "--omp-thinking-minimal",
	thinkingLow: "--omp-thinking-low",
	thinkingMedium: "--omp-thinking-medium",
	thinkingHigh: "--omp-thinking-high",
	thinkingXhigh: "--omp-thinking-xhigh",
};

const CHROME_OVERLAY_BLOCKLIST = new Set<ThemeTokenKey>([
	"--omp-accent",
	"--omp-sidebar-bg",
	"--omp-titlebar-bg",
	"--omp-btn-primary-bg",
]);

const AGENT_THEME_SETTING_PATHS = ["theme.dark", "theme.light"] as const;

/** Agent theme names keyed by GUI base scheme; null until the first settings sync lands. */
let agentThemeNames: { dark: string; light: string } | null = null;
/** CSS vars currently driven by the overlay (null = overlay inactive). */
let agentOverrides: Partial<Record<ThemeTokenKey, string>> | null = null;
/**
 * scheme:name of the last applied overlay. Combined with an intactness probe
 * so same-value data-theme refires (font-size changes, boot) skip re-fetching.
 */
let lastOverlaySignature: string | null = null;
/** Monotonic id — a slow get_theme_colors response must never clobber a newer overlay. */
let agentThemeRequestId = 0;
let agentThemeSettingsRequestId = 0;

/**
 * Fetches one agent theme's resolved colors from the sidecar and maps them
 * onto GUI tokens. Returns null when the theme can't be resolved (unknown
 * name, sidecar down) so callers fall back to the plain named theme.
 */
async function fetchAgentThemeOverrides(name: string): Promise<Partial<Record<ThemeTokenKey, string>> | null> {
	let colors: Record<string, string> | undefined;
	try {
		const res = await window.omp.rpc.getThemeColors(name);
		if (!res.success) return null;
		colors = (res.data as RpcThemeColorsResult | undefined)?.colors;
	} catch {
		return null;
	}
	if (!colors || typeof colors !== "object") return null;
	const overrides: Partial<Record<ThemeTokenKey, string>> = {};
	for (const [token, cssVar] of Object.entries(TRANSCRIPT_OVERLAY_VARS)) {
		if (CHROME_OVERLAY_BLOCKLIST.has(cssVar)) continue;
		const value = colors[token];
		if (typeof value === "string" && value !== "") overrides[cssVar] = value;
	}
	return overrides;
}

/**
 * Writes the overlay on top of whatever base is active: each override becomes
 * an inline custom property, and vars the previous overlay no longer covers
 * are restored to the named theme's inline tokens (or dropped back to the
 * stylesheet while the "system" selection is stylesheet-driven).
 */
function applyAgentOverrides(next: Partial<Record<ThemeTokenKey, string>> | null): void {
	const style = document.documentElement.style;
	if (agentOverrides) {
		for (const key of Object.keys(agentOverrides) as ThemeTokenKey[]) {
			if (next && key in next) continue;
			const base = baseThemeTokens?.[key];
			if (base !== undefined) style.setProperty(key, base);
			else style.removeProperty(key);
		}
	}
	if (next) {
		for (const [key, value] of Object.entries(next)) {
			if (typeof value === "string") style.setProperty(key, value);
		}
	}
	agentOverrides = next;
}

/**
 * True while every var of the active overlay is still present inline.
 * applyTheme() clears inline tokens on base-scheme switches; this detects
 * that wipe so the overlay gets re-applied on top.
 */
function agentOverridesIntact(): boolean {
	if (!agentOverrides) return true;
	const style = document.documentElement.style;
	for (const key of Object.keys(agentOverrides) as ThemeTokenKey[]) {
		if (style.getPropertyValue(key) === "") return false;
	}
	return true;
}

/**
 * Resolves which agent theme (if any) applies to the current GUI base scheme
 * and re-layers it. No-ops until data-theme exists — the App boot effects set
 * it synchronously and the MutationObserver re-fires once they do.
 */
async function refreshAgentThemeOverrides(): Promise<void> {
	const attr = document.documentElement.getAttribute("data-theme");
	if (attr !== "dark" && attr !== "light") return;
	const name = agentThemeNames?.[attr] ?? "";
	if (name === "") {
		agentThemeRequestId++;
		lastOverlaySignature = null;
		applyAgentOverrides(null);
		return;
	}
	const signature = `${attr}:${name}`;
	if (signature === lastOverlaySignature && agentOverridesIntact()) return;
	const requestId = ++agentThemeRequestId;
	const overrides = await fetchAgentThemeOverrides(name);
	if (requestId !== agentThemeRequestId) return;
	lastOverlaySignature = overrides ? signature : null;
	applyAgentOverrides(overrides);
}

/** Reads theme.dark / theme.light from the agent and forces a re-layer. */
async function syncAgentThemeSettings(): Promise<void> {
	if (!acceptsActiveTabEvents()) return;
	const requestId = ++agentThemeSettingsRequestId;
	try {
		const res = await window.omp.rpc.getSettings([...AGENT_THEME_SETTING_PATHS]);
		if (requestId !== agentThemeSettingsRequestId || !acceptsActiveTabEvents()) return;
		const values = res.success ? (res.data as { values?: Record<string, unknown> } | undefined)?.values : undefined;
		const dark = values?.["theme.dark"];
		const light = values?.["theme.light"];
		agentThemeNames = {
			dark: typeof dark === "string" ? dark : "",
			light: typeof light === "string" ? light : "",
		};
	} catch {
		if (requestId !== agentThemeSettingsRequestId || !acceptsActiveTabEvents()) return;
		agentThemeNames = null;
	}
	lastOverlaySignature = null;
	await refreshAgentThemeOverrides();
}

/**
 * Starts layering the agent's theme.dark / theme.light TUI themes on top of
 * the active GUI theme: the theme matching the GUI's current base scheme
 * (theme.dark while data-theme is dark, theme.light while light) is resolved
 * into inline CSS var overrides over the GUI named theme, re-applied on every
 * config_update frame and on every GUI theme/scheme change (observed via
 * data-theme). Unset or unresolvable agent themes leave the GUI named theme
 * untouched. Call once at App boot; the returned teardown restores the base.
 */
export function initAgentThemeSync(): () => void {
	void syncAgentThemeSettings();
	const unsubscribe = window.omp.events.onConfigUpdate(() => {
		if (acceptsActiveTabEvents()) void syncAgentThemeSettings();
	});
	const unsubscribeRoute = onActiveTabRouteSettled(() => void syncAgentThemeSettings());
	const observer = new MutationObserver(() => {
		void refreshAgentThemeOverrides();
	});
	observer.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] });
	return () => {
		unsubscribe();
		unsubscribeRoute();
		observer.disconnect();
		agentThemeRequestId++;
		agentThemeSettingsRequestId++;
		agentThemeNames = null;
		lastOverlaySignature = null;
		applyAgentOverrides(null);
	};
}
